### ISSUE TITLE
Warning: Implicit declaration of function 'CARenderServerRenderDisplay' is invalid in C99

### ISSUE THREAD

**Issue by cloudycliff** [k06a/UIView-FastScreenshot#1]
I'm using Xcode5 on 10.9.1 targeting iOS7 and I got the warning:
"Implicit declaration of function 'CARenderServerRenderDisplay' is invalid in C99"

Although the project can compile and works fine, I wonder where does the function CARenderServerRenderDisplay come from?

**Comment by k06a** [comment]
This is an Apple private API function. It can be a problem for AppStore publishing.
