### ISSUE TITLE
Will this repo support iOS9?

### ISSUE THREAD

**Issue by zavierxu** [k06a/UIView-FastScreenshot#4]
Seems iOS9 removed CoreSurface Framworks, any idea to capture screenshot in iOS9?

**Comment by k06a** [comment]
I think you can get this framework anywhere and add to project. Maybe it will require additional framework.

Or maybe just try new official ReplayKit?

**Comment by zavierxu** [comment]
You mean add this framework as other third party framework? Hmmmm, hope it will be an easy work, though i have no idea about its requirements. 

ReplayKit seems a better choice, LoL

Thanks anyway, I learned a lot from your code!

**Comment by k06a** [comment]
You are welcome! May be you'll find something interesting in other projects originated by me.

For example:
https://github.com/k06a/RTLButton (we need to develop TopToBottom and BottomToTop buttons)
https://github.com/k06a/UIImage-DecompressAndMap
